# wrangler.toml
name = "yamisskey-anonote"
pages_build_output_dir = "public"
compatibility_date = "2024-10-24"

# KV Namespace binding
kv_namespaces = [{ binding = "RATE_LIMIT_KV", id = "YOUR_KV_NAMESPACE_ID" }]

[vars]
MISSKEY_URL = "https://example.com"
MISSKEY_TOKEN = "TOKEN"

